
country_map = {
	'in': "India",	
	'ae': "United Arab Emirates",	
	'ar': "Argentine",	
	'at': "Austria",	
	'au': "Australia",	
	'be': "Belgium",	
	'bg': "Bulgaria",	
	'br': "Brazil",	
	'ca': "Canada",	
	'ch': "The Swiss Confederation",	
	'cn': "China",	
	'co': "Colombia",	
	'cu': "Cuba",	
	'cz': "Czech Republic",	
	'de': "Federal Republic of Germany",	
	'eg': "Arab Republic of Egypt",	
	'es': "Kingdom of Spain",	
	'fr': "French Republic",	
	'gb': "United Kingdom of Great Britain and Northern Ireland",	
	'gr': "Hellenic Republic",	
	'hk': "Hong Kong Special Administrative Region of China",	
	'hu': "Hungary",	
	'id': "Indonesia",	
	'ie': "Ireland",	
	'il': "Israel",	
	'is': "Iceland",	
	'it': "Italy",	
	'jp': "Japan",	
	'kr': "Korea",	
	'lt': "Lithuania",	
	'lv': "Latvia",	
	'ma': "Morocco",	
	'mx': "Mexico",	
	'my': "Malaysia",	
	'ng': "Nigeria",	
	'nl': "Netherlands",	
	'no': "Norway",	
	'nz': "New Zealand",	
	'ph': "Philippines",	
	'pk': "Pakistan",	
	'pl': "Poland",	
	'pt': "Portugal",	
	'ro': "Romania",	
	'rs': "Serbia",	
	'ru': "Uruguay",	
	'sa': "Saudi Arabia",	
	'se': "Sweden",	
	'sg': "Singapore",	
	'si': "Slovenia",	
	'sk': "Slovakia",	
	'th': "Thailand",	
	'tr': "Turkey",	
	'tw': "Taiwan",	
	'ua': "Ukraine",	
	'us': "United States of America",	
	've': "Venezuela",	
	'za': "South Africa",
	}

language_map = {
	'en': "English",	
	'ar': "Arabic",	
	'de': "German",	
	'es': "Spanish",	
	'fr': "French",	
	'he': "Hebrew",	
	'it': "Italian",	
	'nl': "Dutch",	
	'no': "Norwegian",	
	'pt': "Portuguese",	
	'ru': "Russian",	
	'se': "Northern Sami",	
	'sv': "Swedish",
	}


if __name__ == '__main__':
	for key, value in country_map.items():
		print(key, value)

	print("lang ###############")
	for key, value in language_map.items():
		print(key, value)